(define (problem simple)
  (:domain sokoban-domain)
  (:objects s1 s2 s3 s4)
  (:init (adjacent s1 s2) (adjacent s2 s1)
         (adjacent s2 s3) (adjacent s3 s2)
         (adjacent s2 s4) (adjacent s4 s2)
         (adjacent_2 s1 s3) (adjacent_2 s3 s1)
         (has_player s1)
         (has_box s2))
  (:goal (has_box s3))
)

